language: minimal
services:
  - docker
branches:
  only:
    - master
script:
  # Static image depends on API so it has to be in this order
  - docker-compose -f docker-compose.build.yml build --pull api
  - docker-compose -f docker-compose.build.yml build --pull static
  - ./push.sh
