version: "3"

# Use these instead of the local directory for building the projects
# to prevent the containers from fighting with external build tools
volumes:
  node_modules:

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=rps
      - POSTGRES_USER=rps
      - POSTGRES_PASSWORD=rps

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

  api:
    build: ./rust_api/
    command: sh -c "rustup default stable && cargo watch -x run"
    tty: true # Colorize output
    volumes:
      - ./api/:/app/rust_api:rw
    depends_on:
      - db
    environment:
      - RUST_BACKTRACE=1
    ports:
      - "8000:8000"

  webapp:
    image: node:10-alpine
    working_dir: /app/webapp
    command: sh -c "npm i && HTTPS=true npm start"
    volumes:
      - ./webapp:/app/webapp:rw
      - node_modules:/app/webapp/node_modules
    environment:
      - NODE_ENV=development
      - RPS_API_HOST=http://api:8000/
    ports:
      - "3000:3000"
