[package]
authors = ["Lucas Pickering <lucas@lucaspickering.me>"]
edition = "2018"
name = "rps"
version = "0.1.0"
[dependencies]
actix-web = "1.0.8"
failure = "*"

[dependencies.diesel]
default-features = false
features = ["chrono", "postgres"]
version = "1.4.2"
